---
name: Validate

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  # https://developers.home-assistant.io/blog/2020/04/16/hassfest
  hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        # yamllint disable rule:line-length
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        # yamllint enable rule:line-length
        with:
          persist-credentials: false

      - name: Run hassfest validation
        # yamllint disable rule:line-length
        uses: home-assistant/actions/hassfest@d05c25388490cd662baef8495e1bc764c3386153 # master
        # yamllint enable rule:line-length

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
          # Remove this 'ignore' key when you have added brand images for
          # your integration. See docs:
          # https://developers.home-assistant.io/docs/creating_integration_file_structure
          # ignore: brands
